# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "changesets", :force => true do |t|
    t.integer  "revision"
    t.string   "author"
    t.text     "message"
    t.datetime "changed_at"
    t.integer  "repository_id"
  end

  add_index "changesets", ["repository_id"], :name => "index_changesets_on_repository_id"

  create_table "repositories", :force => true do |t|
    t.string "name"
    t.string "path"
    t.string "permalink"
  end

end
