# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "repositories", :force => true do |t|
    t.string "name"
    t.string "path"
    t.string "permalink"
  end

end
