class InstallController < ApplicationController
  skip_before_filter :check_for_repository
  before_filter :check_installed, :except => :test_install
  layout 'install'

  def index
    if session[:installing]
      @repository = Repository.find(:first)
      session[:installing] = nil
      authenticate_with_open_id do |result, identity_url|
        if result.successful? && @current_user = User.find_or_create_by_identity_url(identity_url)
          session[:user_id] = @current_user.id
          render :action => 'install'
        else
          @error = result.message || "Sorry, no user by that identity URL exists (#{identity_url})"
          render :action => 'index'
        end
      end
    else
      @repository = Repository.new
    end
  end
  
  def install
    unless !params[:domain].blank? && params[:domain] =~ evil_regex
      raise "bad domain!"
    end

    @repository = Repository.new(params[:repository])
    unless @repository.valid?
      render :action => 'index'
      return
    end

    require 'net/http'
    res = Net::HTTP.post_form(URI.parse(Warehouse.forum_url % params[:license]), 'install[domain]' => params[:domain])
    if res.code != '200'
      raise res.body
    end

    Warehouse.domain = params[:domain]

    tmpl = <<-END
# This file is auto generated by the installer
#
require 'warehouse'
# set licensed domain name
Warehouse.domain = ":domain"
END
    File.open(File.join(RAILS_ROOT, 'config', 'initializers', 'warehouse.rb'), 'w') do |f|
      f.write tmpl.strip.gsub(/:domain/, Warehouse.domain)
    end
    
    if @repository.save
      session[:installing] = true
      authenticate_with_open_id
    else
      render :action => 'index'
    end
  rescue
    @error = $!.message
    render :template => 'layouts/error'
  end
  
  if RAILS_ENV == 'development'
    def test_install
      # @repository = Repository.new(:name => 'test', :path => '/foo/bar/baz')
      @repository = Repository.find(4)
      render :action => 'install'
    end
  end
  
  protected
    def check_installed
      if current_repository && session[:installing].nil?
        redirect_to root_path
        false
      else
        true
      end
    end

    # this regex is the stuff nightmares are made of
    # thanks to shaun inman
    # http://www.shauninman.com/archive/2006/05/08/validating_domain_names
    #
    # put down here because this monstrosity messed with textmate's syntax highlighting
    def evil_regex
      /^([a-z0-9]([-a-z0-9]*[a-z0-9])?\.)+((a[cdefgilmnoqrstuwxz]|aero|arpa)|(b[abdefghijmnorstvwyz]|biz)|(c[acdfghiklmnorsuvxyz]|cat|com|coop)|d[ejkmoz]|(e[ceghrstu]|edu)|f[ijkmor]|(g[abdefghilmnpqrstuwy]|gov)|(h[kmnrtu]#{RAILS_ENV=='test'?'|host':''})|(i[delmnoqrst]|info|int)|(j[emop]|jobs)|k[eghimnprwyz]|l[abcikrstuvy]|(m[acdghklmnopqrstuvwxyz]|mil|mobi|museum)|(n[acefgilopruz]|name|net)|(om|org)|(p[aefghklmnrstwy]|pro)|qa|r[eouw]|s[abcdeghijklmnortvyz]|(t[cdfghjklmnoprtvwz]|travel)|u[agkmsyz]|v[aceginu]|w[fs]|y[etu]|z[amw])$/
    end
end
