class InstallController < ApplicationController
  skip_before_filter :check_for_repository
  before_filter :check_installed
  layout 'install'

  def index
    @repository = Repository.new
  end
  
  def install
    unless !params[:domain].blank? && params[:domain] =~ evil_regex
      raise "bad domain!"
    end

    @repository = Repository.new(params[:repository])
    unless @repository.valid?
      render :action => 'index'
      return
    end

    require 'net/http'
    res = Net::HTTP.post_form(URI.parse(Warehouse.forum_url % params[:license]), 'install[domain]' => params[:domain])
    if res.code != '200'
      raise res.body
    end

    Warehouse.domain = params[:domain]

    tmpl = <<-END
# This file is auto generated by the installer
#
require 'warehouse'
# set licensed domain name
Warehouse.domain = ":domain"
END
    File.open(File.join(RAILS_ROOT, 'config', 'initializers', 'warehouse.rb'), 'w') do |f|
      f.write tmpl.strip.gsub(/:domain/, Warehouse.domain)
    end
    
    unless @repository.save
      render :action => 'index'
    end
  rescue
    @error = $!.message
    render :template => 'layouts/error'
  end
  
  protected
    def check_installed
      if current_repository
        redirect_to root_path
        false
      else
        true
      end
    end

    # this regex is the stuff nightmares are made of
    # thanks to shaun inman
    # http://www.shauninman.com/archive/2006/05/08/validating_domain_names
    #
    # put down here because this monstrosity messed with textmate's syntax highlighting
    def evil_regex
      /^([a-z0-9]([-a-z0-9]*[a-z0-9])?\.)+((a[cdefgilmnoqrstuwxz]|aero|arpa)|(b[abdefghijmnorstvwyz]|biz)|(c[acdfghiklmnorsuvxyz]|cat|com|coop)|d[ejkmoz]|(e[ceghrstu]|edu)|f[ijkmor]|(g[abdefghilmnpqrstuwy]|gov)|(h[kmnrtu]#{RAILS_ENV=='test'?'|host':''})|(i[delmnoqrst]|info|int)|(j[emop]|jobs)|k[eghimnprwyz]|l[abcikrstuvy]|(m[acdghklmnopqrstuvwxyz]|mil|mobi|museum)|(n[acefgilopruz]|name|net)|(om|org)|(p[aefghklmnrstwy]|pro)|qa|r[eouw]|s[abcdeghijklmnortvyz]|(t[cdfghjklmnoprtvwz]|travel)|u[agkmsyz]|v[aceginu]|w[fs]|y[etu]|z[amw])$/
    end
end
